### ISSUE TITLE
Sorry i must say it

### ISSUE THREAD

**Issue by rainbowjose** [FN-FAL113/cs2-server-picker#15]
Great software. Thank you for your great work. How i can donate you?

**Comment by FN-FAL113** [comment]
> Great software. Thank you for your great work. How i can donate you?

Thank you for the awesome feedback! I can accept paypal donations through my mother's paypal personal account.

**Comment by rainbowjose** [comment]
Done. Thank you.

**Comment by FN-FAL113** [comment]
> Done. Thank you.

I'm very glad for the donation and for showing appreciation! Thank you and have a good day ❤️😊

**Comment by FN-FAL113** [comment]
> Done. Thank you.

Hello, sorry to bother you on this, since my mother's paypal account is a new one, the current donation got on hold. may I ask a favor to check the donation transaction details for an "Confirm Shipment Received" button or link. If it exists, you may confirm it by clicking the button. 
Example from google images: 
![image](https://github.com/FN-FAL113/cs2-server-picker/assets/88238718/224e484a-bb3e-498c-bc49-7ba2be19da14)

**Comment by FN-FAL113** [comment]
![image](https://github.com/FN-FAL113/cs2-server-picker/assets/88238718/9c0dd4f2-ba97-4f46-ba94-03d0f22cff41)
These are the steps to confirm the receipt. Once again I really appreciate the donation (its my first ever and really helps a lot).
