### ISSUE TITLE
Where did you manage to get the IPs from?

### ISSUE THREAD

**Issue by YoucefNabil** [FN-FAL113/cs2-server-picker#68]
say one were to do the same for other games (like fortnite, call of duty), or even other valve games like deadlock
how did you manage to find the ips specifically pertaining to matchmaking?
I have found the ranges that valve uses in this database, but it's really hard to guess what's used for what or from where
https://bgp.he.net/AS32590#_prefixes
It would be useful to know for updating purposes

**Comment by alexitx** [comment]
> I have found the ranges that valve uses in this database, but it's really hard to guess what's used for what or from where
> https://bgp.he.net/AS32590#_prefixes

This looks like the entire ranges registered for Valve.

For CS2, the official servers are part of the [Steam Datagram Relay](https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay), which is Valve's private network of datacenters that handles routing and game traffic. I'm not sure if this applies to all Valve games, but it would make sense. This is the API for CS2: https://api.steampowered.com/ISteamApps/GetSDRConfig/v1/?appid=730.

Some locations ("POP", points of presence) have game servers, while others only have relays that route traffic. This is done for security and stability, so blocking some relays won't block the actual game server and the connection may be routed trough the next best relay.

> say one were to do the same for other games (like fortnite, call of duty), or even other valve games like deadlock

I can't say much for these games as I don't play them. Since they have nothing to do with Steam, I imagine they have their own infrastructures or rent from providers like AWS, Azure, Akamai, etc.

Epic Games have Epic Online Services and this is what I managed to find from a quick search:
https://www.epicgames.com/help/en-US/c-Category_TechnicalSupport/a000086907
https://dev.epicgames.com/docs/game-services
https://dev.epicgames.com/docs/web-api-ref
The documentation states that access tokens are required in order to access the Web APIs. If you're also not a game developer I'm not sure how it will work.
